{% set table_metadata = { 
	 "table_definition":" 
		CREATE TABLE IF NOT EXISTS dw.fact_pnl_commercial ( 
	fact_pnl_commercial_id bigint identity NOT NULL  ,
	org_tranagg_id       bigint    ,
	org_dataprocessing_ruleid integer    ,
	mapped_dataprocessing_ruleid integer    ,
	dataprocessing_outcome_key integer    ,
	bar_acct             varchar(6)    ,
	bar_currtype         varchar(6)    ,
	posting_week_enddate date    ,
	fiscal_month_id      integer    ,
	scenario_id          integer    ,
	source_system_id     integer    ,
	business_unit_key    bigint    ,
	customer_key         bigint    ,
	product_key          bigint    ,
	org_bar_custno       varchar(30)    ,
	org_bar_product      varchar(30)    ,
	org_bar_brand        varchar(30)    ,
	mapped_bar_custno    varchar(30)    ,
	mapped_bar_product   varchar(30)    ,
	mapped_bar_brand     varchar(30)    ,
	org_soldtocust       varchar(30)    ,
	org_shiptocust       varchar(30)    ,
	org_material         varchar(30)    ,
	alloc_soldtocust     varchar(30)    ,
	alloc_shiptocust     varchar(30)    ,
	alloc_material       varchar(30)    ,
	alloc_bar_product    varchar(30)    ,
	amt                  decimal(38,8)    ,
	tran_volume          decimal(19,8)    ,
	sales_volume         decimal(38,8)    ,
	uom                  varchar(15)    ,
	sales_invoiced       decimal(38,8)    ,
	sales_freight_income decimal(38,8)    ,
	product_sales_export decimal(38,8)    ,
	product_sales_domenstic_total decimal(38,8)    ,
	fob_invoice_sale     decimal(38,8)    ,
	rental_sales         decimal(38,8)    ,
	destroy_in_field     decimal(38,8)    ,
	product_sales        decimal(38,8)    ,
	billable_service_revenue decimal(38,8)    ,
	contract_service_revenue decimal(38,8)    ,
	install_revenue      decimal(38,8)    ,
	service_and_installation_sales decimal(38,8)    ,
	franchise_revenue    decimal(38,8)    ,
	royalty_revenue      decimal(38,8)    ,
	other_sales_revenue_total decimal(38,8)    ,
	returns_domestic     decimal(38,8)    ,
	returns_export       decimal(38,8)    ,
	sales_returns        decimal(38,8)    ,
	rsa_and_price_adjustments decimal(38,8)    ,
	allowances_total     decimal(38,8)    ,
	rebates              decimal(38,8)    ,
	coop_advertising     decimal(38,8)    ,
	cashdiscount_domestic decimal(38,8)    ,
	cashdiscount_export  decimal(38,8)    ,
	cash_discount_total  decimal(38,8)    ,
	fillrate_fine        decimal(38,8)    ,
	fob_deductions       decimal(38,8)    ,
	discounts_allow_domestic decimal(38,8)    ,
	discounts_allow_export decimal(38,8)    ,
	discounts_and_allowexcl_coop_adv decimal(38,8)    ,
	freight_domestic     decimal(38,8)    ,
	freight_export       decimal(38,8)    ,
	sales_freight        decimal(38,8)    ,
	customer_considerations decimal(38,8)    ,
	sales_adjustments_other decimal(38,8)    ,
	sales_deduction_other decimal(38,8)    ,
	standard_material_cost_domestic decimal(38,8)    ,
	standard_material_cost_fob decimal(38,8)    ,
	standard_material_cost_export decimal(38,8)    ,
	standard_material_cost_serv_install decimal(38,8)    ,
	standard_material_cost_serv_install_3p decimal(38,8)    ,
	standard_material_cost decimal(38,8)    ,
	cos_trd_domestic_labor decimal(38,8)    ,
	cos_trd_export_labor decimal(38,8)    ,
	std_labor_cost_manuf decimal(38,8)    ,
	cos_service          decimal(38,8)    ,
	cos_monitoring       decimal(38,8)    ,
	cos_installations    decimal(38,8)    ,
	std_labor_cos_serv_install decimal(38,8)    ,
	std_labor_cos_serv_install_3p decimal(38,8)    ,
	std_labor_cos        decimal(38,8)    ,
	std_oh_cos_serv_install decimal(38,8)    ,
	std_oh_cos_serv_install_3p decimal(38,8)    ,
	std_oh_cos_export    decimal(38,8)    ,
	std_oh_cos           decimal(38,8)    ,
	free_goods_cos       decimal(38,8)    ,
	targeted_funds_cos   decimal(38,8)    ,
	free_goods_total     decimal(38,8)    ,
	cos_freight_outbound decimal(38,8)    ,
	merchandising_cos    decimal(38,8)    ,
	rental_cos           decimal(38,8)    ,
	gross_sales          decimal(38,8)    ,
	allowances           decimal(38,8)    ,
	invoice_sales        decimal(38,8)    ,
	sales_deduction      decimal(38,8)    ,
	net_sales            decimal(38,8)    ,
	std_cos              decimal(38,8)    ,
	total_cos            decimal(38,8)    ,
	std_gross_margin     decimal(38,8)    ,
	audit_loadts         date  NOT NULL  ,
	dim_transactional_attributes_id varchar(300)    
 ) 
	"
}%} 

{{ config(materialized = "ephemeral") }}
{% do run_query(table_metadata.table_definition) %}