{% set table_metadata = { 
	 "table_definition":" 
		CREATE TABLE IF NOT EXISTS ref_data.calendar ( 
	dy_id                integer    ,
	dy_dte               timestamp    ,
	absolute_dy_nbr      integer    ,
	absolute_wk_nbr      integer    ,
	absolute_mth_nbr     integer    ,
	absolute_qtr_nbr     integer    ,
	dy_in_wk_nbr         integer    ,
	dy_in_wk_name        varchar(200)    ,
	julian_dy_nbr        integer    ,
	clndr_wk_nbr         varchar(200)    ,
	clndr_wk_id          varchar(200)    ,
	clndr_mth_nbr        integer    ,
	clndr_mth_id         varchar(200)    ,
	clndr_mth_name       varchar(200)    ,
	clndr_qtr_nbr        integer    ,
	clndr_qtr_id         varchar(200)    ,
	clndr_qtr_name       varchar(200)    ,
	clndr_yr_id          integer    ,
	clndr_dy_in_mth_nbr  integer    ,
	is_first_dy_in_clndr_mth_flag varchar(1)    ,
	is_last_dy_in_clndr_mth_flag varchar(1)    ,
	wk_begin_dte         timestamp    ,
	wk_end_dte           timestamp    ,
	fmth_begin_dte       timestamp    ,
	fmth_end_dte         timestamp    ,
	fqtr_begin_dte       timestamp    ,
	fqtr_end_dte         timestamp    ,
	fyr_begin_dte        timestamp    ,
	fyr_end_dte          timestamp    ,
	fwk_nbr              integer    ,
	fwk_id               integer    ,
	fwk_cd               varchar(200)    ,
	fmth_nbr             integer    ,
	fmth_id              integer    ,
	fmth_cd              varchar(200)    ,
	fmth_name            varchar(200)    ,
	fmth_short_name      varchar(200)    ,
	fqtr_nbr             integer    ,
	fqtr_id              integer    ,
	fqtr_cd              varchar(200)    ,
	fqtr_name            varchar(200)    ,
	fyr_id               integer    ,
	fdy_in_mth_nbr       integer    ,
	fscl_days_remaining_in_mth integer    ,
	fdy_in_qtr_nbr       integer    ,
	fscl_days_remaining_in_qtr integer    ,
	fdy_in_yr_nbr        integer    ,
	fscl_days_remaining_in_yr integer    ,
	fwk_in_mth_nbr       integer    ,
	fwk_in_qtr           integer    ,
	is_wk_dy_flag        varchar(1)    ,
	is_weekend_flag      varchar(1)    ,
	is_first_dy_of_fwk_flag varchar(1)    ,
	is_last_dy_of_fwk_flag varchar(1)    ,
	is_first_dy_of_fmth_flag varchar(1)    ,
	is_last_dy_of_fmth_flag varchar(1)    ,
	is_first_dy_of_fqtr_flag varchar(1)    ,
	is_last_dy_of_fqtr_flag varchar(1)    ,
	is_first_dy_of_fyr_flag varchar(1)    ,
	is_last_dy_of_fyr_flag varchar(1)    ,
	season_name          varchar(200)    ,
	holiday_name         varchar(200)    ,
	holiday_season_name  varchar(200)    ,
	holiday_observed_name varchar(200)    ,
	special_event_name   varchar(200)    ,
	etl_batch_id         varchar(200)    ,
	original_filename    varchar(200)    
 ) 
	"
}%} 

{{ config(materialized = "ephemeral") }}
{% do run_query(table_metadata.table_definition) %}