CREATE OR REPLACE PROCEDURE public.sp_sbd_dm_material_master_insert()
	LANGUAGE plpgsql
AS $$
	
  BEGIN
	INSERT INTO global_pl.material_master_temp
		(ERP_MATERIAL_NUMBER ,ERP_MATERIAL_DESCRIPTION ,ERP_MATERIAL_CATEGORY ,ERP_CONTAINER_REQUIREMENTS ,ERP_GENERIC_MATERIAL_WITH_LOGISTICAL_VARIANTS ,ERP_OLD_MATERIAL_NUMBER ,ERP_BRAND ,ERP_WIDTH ,ERP_GROSS_WEIGHT ,ERP_PURCHASE_ORDER_UoM ,ERP_SOURCE_OF_SUPPLY ,ERP_PROCUREMENT_RULE ,ERP_CAD_INDICATOR ,ERP_QUALITY_CONVERSION_METHOD ,ERP_MATERIAL_COMPLETION_LEVEL ,ERP_INTERNAL_OBJECT_NUMBER ,ERP_VALID_FROM_DATE ,ERP_EAN_UPC ,ERP_PURHCASING_VALUE_KEY ,ERP_UNIT_OF_WEIGHT_PACKAGING ,ERP_ALLOWED_PACKAGING_WEIGHT ,ERP_VOLUME_UNIT ,ERP_ALLOWED_PACKAGING_VOLUME ,ERP_WEIGHT_UNIT ,ERP_SIZE_DIMENSIONS ,ERP_HEIGHT ,ERP_MATERIAL_GROUP ,ERP_INDUSTRY_SECTOR ,ERP_MATERIAL_TYPE ,ERP_NET_WEIGHT ,ERP_PRODUCT_HIERARCHY ,ERP_DIVISION ,ERP_HAZARDOUS_MATERIAL_NUMBER ,ERP_TRANSPORTATION_GROUP ,ERP_PACKAGING_MATERIAL_TYPE ,ERP_GLOBAL_PRODUCT_HIERARCHY ,ERP_SOURCE ,ETL_CRTE_USER ,ETL_CRTE_TS)
			(
				Select MATNR ,NULL ,ATTYP ,BEHVO ,BFLME ,BISMT ,NULL ,BREIT ,BRGEW ,BSTME ,BWSCL ,BWVOR ,CADKZ ,CMETH ,COMPL ,CUOBF ,DATAB::date ,EAN11 ,EKWSL ,ERGEI ,ERGEW ,ERVOE ,ERVOL ,GEWEI ,GROES ,HOEHE ,MATKL ,MBRSH ,MTART ,NTGEW ,PRDHA ,SPART ,STOFF ,TRAGR ,VHART ,WRKST ,'C11','etl_user',to_date(GETDATE(),'yyyyMMdd') FROM bods.c11_0material_attr_current
				UNION ALL
				Select MATNR ,NULL ,ATTYP ,BEHVO ,BFLME ,BISMT ,NULL ,BREIT ,BRGEW ,BSTME ,BWSCL ,BWVOR ,CADKZ ,CMETH ,COMPL ,CUOBF ,DATAB::date ,EAN11 ,EKWSL ,ERGEI ,ERGEW ,ERVOE ,ERVOL ,GEWEI ,GROES ,HOEHE ,MATKL ,MBRSH ,MTART ,NTGEW ,PRDHA ,SPART ,STOFF ,TRAGR ,VHART ,WRKST ,'E03','etl_user',to_date(GETDATE(),'yyyyMMdd') FROM  bods.e03_0material_attr_current
				UNION ALL
				Select MATNR ,NULL ,ATTYP ,BEHVO ,BFLME ,BISMT ,NULL ,BREIT ,BRGEW ,BSTME ,BWSCL ,BWVOR ,CADKZ ,CMETH ,COMPL ,CUOBF ,DATAB::date ,EAN11 ,EKWSL ,ERGEI ,ERGEW ,ERVOE ,ERVOL ,GEWEI ,GROES ,HOEHE ,MATKL ,MBRSH ,MTART ,NTGEW ,PRDHA ,SPART ,STOFF ,TRAGR ,VHART ,WRKST ,'SHP','etl_user',to_date(GETDATE(),'yyyyMMdd') FROM   bods.extr_shp_material_attr_current
				UNION ALL
				Select MATNR ,NULL ,ATTYP ,BEHVO ,BFLME ,BISMT ,NULL ,BREIT ,BRGEW ,BSTME ,BWSCL ,BWVOR ,CADKZ ,CMETH ,COMPL::numeric(38,10) ,CUOBF ,DATAB::date ,EAN11 ,EKWSL ,ERGEI ,ERGEW ,ERVOE ,ERVOL ,GEWEI ,GROES ,HOEHE ,MATKL ,MBRSH ,MTART ,NTGEW ,PRDHA ,SPART ,STOFF ,TRAGR ,VHART ,WRKST ,'P10','etl_user',to_date(GETDATE(),'yyyyMMdd') FROM  bods.extr_p10_0material_attr_current
				limit 1000
			);

  RAISE INFO 'Ran SP Successfull';
  
END;

$$
;
