
		(  
			Select t.BAR_ACCT AS col ,
t.BAR_AMT AS col ,
t.BAR_BRAND AS col ,
t.BAR_BU AS col ,
t.BAR_CURRTYPE AS col ,
t.BAR_CUSTNO AS col ,
t.BAR_ENTITY AS col ,
t.BAR_FUNCTION AS col ,
t.BAR_PERIOD AS col ,
t.BAR_PRODUCT AS col ,
t.BAR_SCENARIO AS col ,
t.BAR_SHIPTO AS col ,
t.BAR_YEAR AS col ,
t.FISCPER AS col ,
t.GL_ACCOUNT AS col ,
t.INT_BRANDGRP AS col ,
t.SEGMENT AS col ,
t.COMPANY_ID AS col ,
t.COST_CENTER AS col ,
NULL AS col ,
t.JOURNAL_ENTRY_ITEM AS col ,
t.JOURNAL_ENTRY AS col ,
NULL AS col ,
NULL AS col ,
t.PRODUCT_ID AS col ,
t.PAYER AS col ,
t.POSTING_DATE AS col ,
t.INVOICED_QUANTITY AS col ,
NULL AS col ,
t.DOCUMENT_TYPE AS col ,
NULL AS col ,
t.SOURCE_DOCUMENT_ID AS col ,
t.PROFIT_CENTER AS col ,
t.CUSTOMER_CHANNEL_CODE AS col ,
NULL AS col ,
t.SHIP_TO_CUSTOMER AS col ,
t.BILL_TO_CUSTOMER AS col ,
NULL AS col ,
NULL AS col ,
t.LOADDATETIME AS col ,
t.ID AS col ,
'BYD'AS col ,
b.bar_entity_currency AS col ,
hfm.bar_amt AS col ,
(t.BAR_AMT * hfm.bar_amt * COALESCE (a.flipsign::INTEGER,1)) AS col ,

to_date(GETDATE(),'yyyyMMdd') AS col ,

'etl_user'     from bods.byd_pl_trans_archive_current t LEFT OUTER JOIN global_pl.bar_acct_attr a ON t.BAR_ACCT = a.bar_account LEFT OUTER JOIN global_pl.bar_entity_attr b ON t.BAR_ENTITY = b.bar_entity LEFT OUTER JOIN bods.hfm_vw_hfm_actual_trans_current hfm ON (t.bar_year = hfm.bar_year AND t.bar_period = hfm.bar_period AND hfm.bar_function = b.bar_entity_currency )  where t.id is not null
		);
		

	(  
		Select t.BAR_ACCT AS col ,
t.BAR_AMT AS col ,
t.BAR_BRAND AS col ,
t.BAR_BU AS col ,
t.BAR_CURRTYPE AS col ,
t.BAR_CUSTNO AS col ,
t.BAR_ENTITY AS col ,
t.BAR_FUNCTION AS col ,
t.BAR_PERIOD AS col ,
t.BAR_PRODUCT AS col ,
t.BAR_SCENARIO AS col ,
t.BAR_SHIPTO AS col ,
t.BAR_YEAR AS col ,
NULL AS col ,
t.ACCT AS col ,
NULL AS col ,
t.CUSTOM1 AS col ,
t.ENTITY AS col ,
t.CUSTOM2 AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.LOADDATETIME AS col ,
t.ID AS col ,
'HFM'AS col ,
b.bar_entity_currency AS col ,
t.bar_amt AS col ,
t.bar_amt AS col ,
to_date(GETDATE(),'yyyyMMdd') AS col ,

'etl_user'  from bods.hfm_vw_hfm_actual_trans_current t  LEFT OUTER JOIN global_pl.bar_acct_attr a ON t.BAR_ACCT = a.bar_account LEFT OUTER JOIN global_pl.bar_entity_attr b ON t.BAR_ENTITY = b.bar_entity 
	);
		

		( 
			select t.BAR_ACCT AS col ,
t.BAR_AMT AS col ,
t.BAR_BRAND AS col ,
t.BAR_BU AS col ,
t.BAR_CURRTYPE AS col ,
t.BAR_CUSTNO AS col ,
t.BAR_ENTITY AS col ,
t.BAR_FUNCTION AS col ,
t.BAR_PERIOD AS col ,
t.BAR_PRODUCT AS col ,
t.BAR_SCENARIO AS col ,
t.BAR_SHIPTO AS col ,
t.BAR_YEAR AS col ,
t.FISCPER AS col ,
t.ACCT AS col ,
NULL AS col ,
t.DEPARTMENT AS col ,
t.COCODE AS col ,
NULL AS col ,
t.DOCUMENT_TYPE AS col ,
NULL AS col ,
t.DOCUMENT_NO AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.TRANSACTION_NO AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.LOADDATETIME AS col ,
t.ID AS col ,
'NAVSTORAGE'AS col ,
b.bar_entity_currency AS col ,
hfm.bar_amt AS col ,
(t.BAR_AMT * hfm.bar_amt * COALESCE (a.flipsign::INTEGER,1)) AS col ,

to_date(GETDATE(),'yyyyMMdd') AS col ,

'etl_user'  FROM bods.nav_storage_pl_trans_current  t LEFT OUTER JOIN global_pl.bar_acct_attr a ON t.BAR_ACCT = a.bar_account LEFT OUTER JOIN global_pl.bar_entity_attr b ON t.BAR_ENTITY = b.bar_entity LEFT OUTER JOIN bods.hfm_vw_hfm_actual_trans_current hfm ON (t.bar_year = hfm.bar_year AND t.bar_period = hfm.bar_period AND hfm.bar_function = b.bar_entity_currency )
		);


		(  
			select t.BAR_ACCT AS col ,
t.BAR_AMT AS col ,
t.BAR_BRAND AS col ,
t.BAR_BU AS col ,
t.BAR_CURRTYPE AS col ,
t.BAR_CUSTNO AS col ,
t.BAR_ENTITY AS col ,
t.BAR_FUNCTION AS col ,
t.BAR_PERIOD AS col ,
t.BAR_PRODUCT AS col ,
t.BAR_SCENARIO AS col ,
t.BAR_SHIPTO AS col ,
t.BAR_YEAR AS col ,
t.FISCPER AS col ,
t.ACCT AS col ,
NULL AS col ,
NULL AS col ,
t.CO_CD AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.TXN_ID AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.BAR_CUSTNO AS col ,
NULL AS col ,
NULL AS col ,
t.LOADDATETIME AS col ,
t.ID AS col ,
 'NAVEUR'AS col ,
b.bar_entity_currency AS col ,
hfm.bar_amt AS col ,
(t.BAR_AMT * hfm.bar_amt * COALESCE (a.flipsign::INTEGER,1)) AS col ,

to_date(GETDATE(),'yyyyMMdd') AS col ,

'etl_user'  FROM bods.nav_eur_pl_trans_current  t LEFT OUTER JOIN global_pl.bar_acct_attr a ON t.BAR_ACCT = a.bar_account LEFT OUTER JOIN global_pl.bar_entity_attr b ON t.BAR_ENTITY = b.bar_entity LEFT OUTER JOIN bods.hfm_vw_hfm_actual_trans_current hfm ON (t.bar_year = hfm.bar_year AND t.bar_period = hfm.bar_period AND hfm.bar_function = b.bar_entity_currency )
		);

		(  
			Select t.BAR_ACCT AS col ,
t.BAR_AMT AS col ,
t.BAR_BRAND AS col ,
t.BAR_BU AS col ,
t.BAR_CURRTYPE AS col ,
t.BAR_CUSTNO AS col ,
t.BAR_ENTITY AS col ,
t.BAR_FUNCTION AS col ,
t.BAR_PERIOD AS col ,
t.BAR_PRODUCT AS col ,
t.BAR_SCENARIO AS col ,
t.BAR_SHIPTO AS col ,
t.BAR_YEAR AS col ,
t.FISCPER AS col ,
t.GLACCOUNT_CODE AS col ,
NULL AS col ,
t.DEPARTMENT_CODE AS col ,
t.CDCCODE AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.VOUCHNO AS col ,
NULL AS col ,
NULL AS col ,
t.PRODUCT_CODE AS col ,
NULL AS col ,
t.POSTING_DATE AS col ,
t.PRODUCT_QTY AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.CUSTOMER_CODE AS col ,
NULL AS col ,
NULL AS col ,
t.LOADDATETIME AS col ,
t.ID AS col ,
'UFIDA'AS col ,
b.bar_entity_currency AS col ,
hfm.bar_amt AS col ,
(t.BAR_AMT * hfm.bar_amt * COALESCE (a.flipsign::INTEGER,1)) AS col ,

to_date(GETDATE(),'yyyyMMdd') AS col ,

'etl_user' FROM bods.ufida_pl_trans_current  t LEFT OUTER JOIN global_pl.bar_acct_attr a ON t.BAR_ACCT = a.bar_account LEFT OUTER JOIN global_pl.bar_entity_attr b ON t.BAR_ENTITY = b.bar_entity LEFT OUTER JOIN bods.hfm_vw_hfm_actual_trans_current hfm ON (t.bar_year = hfm.bar_year AND t.bar_period = hfm.bar_period AND hfm.bar_function = b.bar_entity_currency )
		);


		(  
			Select t.BAR_ACCT AS col ,
t.BAR_AMT AS col ,
t.BAR_BRAND AS col ,
t.BAR_BU AS col ,
t.BAR_CURRTYPE AS col ,
t.BAR_CUSTNO AS col ,
t.BAR_ENTITY AS col ,
t.BAR_FUNCTION AS col ,
t.BAR_PERIOD AS col ,
t.BAR_PRODUCT AS col ,
t.BAR_SCENARIO AS col ,
t.BAR_SHIPTO AS col ,
t.BAR_YEAR AS col ,
t.FISCPER AS col ,
t.ACCT AS col ,
NULL AS col ,
t.ICP_CD AS col ,
t.CO_CD AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.TXN_ID AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.POST_DTE AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.LOADDATETIME AS col ,
t.ID AS col ,
'ORCHBGI'AS col ,
b.bar_entity_currency AS col ,
hfm.bar_amt AS col ,
(t.BAR_AMT * hfm.bar_amt * COALESCE (a.flipsign::INTEGER,1)) AS col ,

to_date(GETDATE(),'yyyyMMdd') AS col ,

'etl_user'   FROM bods.orch_bgi_pl_trans_current    t LEFT OUTER JOIN global_pl.bar_acct_attr a ON t.BAR_ACCT = a.bar_account LEFT OUTER JOIN global_pl.bar_entity_attr b ON t.BAR_ENTITY = b.bar_entity LEFT OUTER JOIN bods.hfm_vw_hfm_actual_trans_current hfm ON (t.bar_year = hfm.bar_year AND t.bar_period = hfm.bar_period AND hfm.bar_function = b.bar_entity_currency )
		);


		(  
			Select t.BAR_ACCT AS col ,
t.BAR_AMT AS col ,
t.BAR_BRAND AS col ,
t.BAR_BU AS col ,
t.BAR_CURRTYPE AS col ,
t.BAR_CUSTNO AS col ,
t.BAR_ENTITY AS col ,
t.BAR_FUNCTION AS col ,
t.BAR_PERIOD AS col ,
t.BAR_PRODUCT AS col ,
t.BAR_SCENARIO AS col ,
t.BAR_SHIPTO AS col ,
t.BAR_YEAR AS col ,
t.FISCPER AS col ,
t.ACCT AS col ,
NULL AS col ,
NULL AS col ,
t.CO_CD AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.TXN_ID AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.POST_DTE AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.LOADDATETIME AS col ,
t.ID AS col ,
'CONT'AS col ,
b.bar_entity_currency AS col ,
hfm.bar_amt AS col ,
(t.BAR_AMT * hfm.bar_amt * COALESCE (a.flipsign::INTEGER,1)) AS col ,

to_date(GETDATE(),'yyyyMMdd') AS col ,

'etl_user'  from bods.cont_pl_trans_current  t LEFT OUTER JOIN global_pl.bar_acct_attr a ON t.BAR_ACCT = a.bar_account LEFT OUTER JOIN global_pl.bar_entity_attr b ON t.BAR_ENTITY = b.bar_entity LEFT OUTER JOIN bods.hfm_vw_hfm_actual_trans_current hfm ON (t.bar_year = hfm.bar_year AND t.bar_period = hfm.bar_period AND hfm.bar_function = b.bar_entity_currency )
		);


		(  
			Select t.BAR_ACCT AS col ,
t.BAR_AMT AS col ,
t.BAR_BRAND AS col ,
t.BAR_BU AS col ,
t.BAR_CURRTYPE AS col ,
t.BAR_CUSTNO AS col ,
t.BAR_ENTITY AS col ,
t.BAR_FUNCTION AS col ,
t.BAR_PERIOD AS col ,
t.BAR_PRODUCT AS col ,
t.BAR_SCENARIO AS col ,
t.BAR_SHIPTO AS col ,
t.BAR_YEAR AS col ,
t.FISCPER AS col ,
t.ACCT AS col ,
NULL AS col ,
t.DEPT AS col ,
t.CO_CD AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.TXN_ID AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.TXN_DTE AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.CUST_NBR AS col ,
NULL AS col ,
NULL AS col ,
t.LOADDATETIME AS col ,
t.ID AS col ,
'MOVEX'AS col ,
b.bar_entity_currency AS col ,
hfm.bar_amt AS col ,
(t.BAR_AMT * hfm.bar_amt * COALESCE (a.flipsign::INTEGER,1)) AS col ,

to_date(GETDATE(),'yyyyMMdd') AS col ,

'etl_user'  from bods.movex_pl_trans_current  t LEFT OUTER JOIN global_pl.bar_acct_attr a ON t.BAR_ACCT = a.bar_account LEFT OUTER JOIN global_pl.bar_entity_attr b ON t.BAR_ENTITY = b.bar_entity LEFT OUTER JOIN bods.hfm_vw_hfm_actual_trans_current hfm ON (t.bar_year = hfm.bar_year AND t.bar_period = hfm.bar_period AND hfm.bar_function = b.bar_entity_currency )
		);		



		(  
			select t.ACCOUNT AS col ,
t.BAR_AMT AS col ,
t.BAR_BRAND AS col ,
t.BAR_BU AS col ,
t.BAR_CURRTYPE AS col ,
t.BAR_CUSTNO AS col ,
t.BAR_ENTITY AS col ,
t.BAR_FUNCTION AS col ,
t.BAR_PERIOD AS col ,
t.BAR_PRODUCT AS col ,
t.BAR_SCENARIO AS col ,
t.BAR_SHIPTO AS col ,
t.BAR_YEAR AS col ,
t.FISCPER AS col ,
t.ACCOUNT AS col ,
NULL AS col ,
t.CODE_B AS col ,
t.COMPANY AS col ,
t.ACCOUNT_GROUP AS col ,
t.VOUCHER_TYPE AS col ,
NULL AS col ,
t.VOUCHER_NO AS col ,
REGEXP_REPLACE(TEXTAS col ,
'[^a-zA-Z0-9\u00E0-\u00FC ]+'AS col ,
'') as TEXT AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.LOADDATETIME AS col ,
t.ID AS col ,
'IFS'AS col ,
b.bar_entity_currency AS col ,
hfm.bar_amt AS col ,
(t.BAR_AMT * hfm.bar_amt * COALESCE (a.flipsign::INTEGER,1)) AS col ,

to_date(GETDATE(),'yyyyMMdd') AS col ,

 'etl_user'  FROM   bods.ifs_pl_trans_current  t LEFT OUTER JOIN global_pl.bar_acct_attr a ON t.BAR_ACCT = a.bar_account LEFT OUTER JOIN global_pl.bar_entity_attr b ON t.BAR_ENTITY = b.bar_entity LEFT OUTER JOIN bods.hfm_vw_hfm_actual_trans_current hfm ON (t.bar_year = hfm.bar_year AND t.bar_period = hfm.bar_period AND hfm.bar_function = b.bar_entity_currency )
		);		

		(  
			select t.BAR_ACCT AS col ,
t.BAR_AMT AS col ,
t.BAR_BRAND AS col ,
t.BAR_BU AS col ,
t.BAR_CURRTYPE AS col ,
t.BAR_CUSTNO AS col ,
t.BAR_ENTITY AS col ,
t.BAR_FUNCTION AS col ,
t.BAR_PERIOD AS col ,
t.BAR_PRODUCT AS col ,
t.BAR_SCENARIO AS col ,
t.BAR_SHIPTO AS col ,
t.BAR_YEAR AS col ,
t.FISCPER AS col ,
t.GL_ACCOUNT AS col ,
NULL AS col ,
NULL AS col ,
t.COMPANY AS col ,
NULL AS col ,
t.JOURNAL_CODE AS col ,
t.JOURNAL_LINE AS col ,
t.JOURNAL_NUM AS col ,
REGEXP_REPLACE(DESCRIPTIONAS col ,
'[^a-zA-Z0-9\u00E0-\u00FC ]+'AS col ,
'') as DESCRIPTION AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.POSTED_DATE AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.GROUPID AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.LOADDATETIME AS col ,
t.ID AS col ,
'NELSON'AS col ,
b.bar_entity_currency AS col ,
hfm.bar_amt AS col ,
(t.BAR_AMT * hfm.bar_amt * COALESCE (a.flipsign::INTEGER,1)) AS col ,

to_date(GETDATE(),'yyyyMMdd') AS col ,

 'etl_user'  FROM   bods.nelson_asmp_pl_trans_current  t LEFT OUTER JOIN global_pl.bar_acct_attr a ON t.BAR_ACCT = a.bar_account LEFT OUTER JOIN global_pl.bar_entity_attr b ON t.BAR_ENTITY = b.bar_entity LEFT OUTER JOIN bods.hfm_vw_hfm_actual_trans_current hfm ON (t.bar_year = hfm.bar_year AND t.bar_period = hfm.bar_period AND hfm.bar_function = b.bar_entity_currency )
		);		



		(  
			select t.BAR_ACCT AS col ,
t.BAR_AMT AS col ,
t.BAR_BRAND AS col ,
t.BAR_BU AS col ,
t.BAR_CURRTYPE AS col ,
t.BAR_CUSTNO AS col ,
t.BAR_ENTITY AS col ,
t.BAR_FUNCTION AS col ,
t.BAR_PERIOD AS col ,
t.BAR_PRODUCT AS col ,
t.BAR_SCENARIO AS col ,
NULL AS col ,
t.BAR_YEAR AS col ,
t.FISCPER AS col ,
t.ACCOUNT AS col ,
NULL AS col ,
t.BUSINESS_AREA AS col ,
NULL AS col ,
t.COST_CENTER AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.PRODUCT_CODE AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.PROFIT_CENTER AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.CUST_NUM AS col ,
NULL AS col ,
NULL AS col ,
t.LOADDATETIME AS col ,
t.ID AS col ,
'AGRESSO'AS col ,
b.bar_entity_currency AS col ,
hfm.bar_amt AS col ,
(t.BAR_AMT * hfm.bar_amt * COALESCE (a.flipsign::INTEGER,1)) AS col ,

to_date(GETDATE(),'yyyyMMdd') AS col ,

'etl_user'  FROM   bods.agresso_pl_trans_current  t LEFT OUTER JOIN global_pl.bar_acct_attr a ON t.BAR_ACCT = a.bar_account LEFT OUTER JOIN global_pl.bar_entity_attr b ON t.BAR_ENTITY = b.bar_entity LEFT OUTER JOIN bods.hfm_vw_hfm_actual_trans_current hfm ON (t.bar_year = hfm.bar_year AND t.bar_period = hfm.bar_period AND hfm.bar_function = b.bar_entity_currency )
		);		



		(  
			select t.BAR_ACCT AS col ,
t.BAR_AMT AS col ,
t.BAR_BRAND AS col ,
t.BAR_BU AS col ,
t.BAR_CURRTYPE AS col ,
t.BAR_CUSTNO AS col ,
t.BAR_ENTITY AS col ,
t.BAR_FUNCTION AS col ,
t.BAR_PERIOD AS col ,
t.BAR_PRODUCT AS col ,
t.BAR_SCENARIO AS col ,
t.BAR_SHIPTO AS col ,
t.BAR_YEAR AS col ,
t.FISCPER AS col ,
t.ACCOUNT AS col ,
NULL AS col ,
t.DEPARTMENT_EXP AS col ,
NULL AS col ,
t.EXPENSES_TYPE AS col ,
t.DOCUMENT_TYPE AS col ,
NULL AS col ,
t.DOCUMENT_ID AS col ,
NULL AS col ,
NULL AS col ,
t.PRODUCT AS col ,
t.BILL_TO_CUSTOMER AS col ,
t.TRANSACTION_DATE AS col ,
t.QTY AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.SHIP_TO_CUSTOMER AS col ,
t.SOLD_TO_CUSTOMER AS col ,
NULL AS col ,
NULL AS col ,
t.LOADDATETIME AS col ,
t.ID AS col ,
'NAV'AS col ,
b.bar_entity_currency AS col ,
hfm.bar_amt AS col ,
(t.BAR_AMT * hfm.bar_amt * COALESCE (a.flipsign::INTEGER,1)) AS col ,

to_date(GETDATE(),'yyyyMMdd') AS col ,

'etl_user'  FROM   bods.nav_assm_pl_trans_current  t LEFT OUTER JOIN global_pl.bar_acct_attr a ON t.BAR_ACCT = a.bar_account LEFT OUTER JOIN global_pl.bar_entity_attr b ON t.BAR_ENTITY = b.bar_entity LEFT OUTER JOIN bods.hfm_vw_hfm_actual_trans_current hfm ON (t.bar_year = hfm.bar_year AND t.bar_period = hfm.bar_period AND hfm.bar_function = b.bar_entity_currency )
		);		



		(  
			select t.BAR_ACCT AS col ,
t.BAR_AMT AS col ,
t.BAR_BRAND AS col ,
t.BAR_BU AS col ,
t.BAR_CURRTYPE AS col ,
t.BAR_CUSTNO AS col ,
t.BAR_ENTITY AS col ,
t.BAR_FUNCTION AS col ,
t.BAR_PERIOD AS col ,
t.BAR_PRODUCT AS col ,
t.BAR_SCENARIO AS col ,
t.BAR_SHIPTO AS col ,
t.BAR_YEAR AS col ,
t.FISCPER AS col ,
t.ACCT AS col ,
NULL AS col ,
NULL AS col ,
t.QAD_ENTITY AS col ,
t.COSTCTR AS col ,
t.DOCUMENT_TYPE AS col ,
NULL AS col ,
t.DOCUMENT_ID AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.BILL_TO_CUSTOMER AS col ,
t.TRANSACTION_DATE AS col ,
t.QUANTITY AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.SOLD_TO_CUSTOMER AS col ,
t.SITE AS col ,
NULL AS col ,
t.LOADDATETIME AS col ,
t.ID AS col ,
'BRAZIL'AS col ,
b.bar_entity_currency AS col ,
hfm.bar_amt AS col ,
(t.BAR_AMT * hfm.bar_amt * COALESCE (a.flipsign::INTEGER,1)) AS col ,

to_date(GETDATE(),'yyyyMMdd') AS col ,

'etl_user'  FROM   bods.qad_brazil_pl_trans_current  t LEFT OUTER JOIN global_pl.bar_acct_attr a ON t.BAR_ACCT = a.bar_account LEFT OUTER JOIN global_pl.bar_entity_attr b ON t.BAR_ENTITY = b.bar_entity LEFT OUTER JOIN bods.hfm_vw_hfm_actual_trans_current hfm ON (t.bar_year = hfm.bar_year AND t.bar_period = hfm.bar_period AND hfm.bar_function = b.bar_entity_currency )
		);		



		(  
			select t.BAR_ACCT AS col ,
t.BAR_AMT AS col ,
t.BAR_BRAND AS col ,
t.BAR_BU AS col ,
t.BAR_CURRTYPE AS col ,
t.BAR_CUSTNO AS col ,
t.BAR_ENTITY AS col ,
t.BAR_FUNCTION AS col ,
t.BAR_PERIOD AS col ,
t.BAR_PRODUCT AS col ,
t.BAR_SCENARIO AS col ,
t.BAR_SHIPTO AS col ,
t.BAR_YEAR AS col ,
t.FISCPER AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.DOCUMENT_TYPE AS col ,
NULL AS col ,
t.DOCUMENT_ID AS col ,
NULL AS col ,
NULL AS col ,
t.PRODUCT AS col ,
t.BILL_TO_CUSTOMER AS col ,
t.POSTING_DATE AS col ,
t.QUANTITY AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.SHIP_TO AS col ,
t.SOLD_TO_CUSTOMER AS col ,
NULL AS col ,
NULL AS col ,
t.LOADDATETIME AS col ,
t.ID AS col ,
'DECH'AS col ,
b.bar_entity_currency AS col ,
hfm.bar_amt AS col ,
(t.BAR_AMT * hfm.bar_amt * COALESCE (a.flipsign::INTEGER,1)) AS col ,

to_date(GETDATE(),'yyyyMMdd') AS col ,

'etl_user'  FROM   bods.qad_dech_pl_trans_current  t LEFT OUTER JOIN global_pl.bar_acct_attr a ON t.BAR_ACCT = a.bar_account LEFT OUTER JOIN global_pl.bar_entity_attr b ON t.BAR_ENTITY = b.bar_entity LEFT OUTER JOIN bods.hfm_vw_hfm_actual_trans_current hfm ON (t.bar_year = hfm.bar_year AND t.bar_period = hfm.bar_period AND hfm.bar_function = b.bar_entity_currency )
		);		



		(  
			select t.BAR_ACCT AS col ,
t.BAR_AMT AS col ,
t.BAR_BRAND AS col ,
t.BAR_BU AS col ,
t.BAR_CURRTYPE AS col ,
t.BAR_CUSTNO AS col ,
t.BAR_ENTITY AS col ,
t.BAR_FUNCTION AS col ,
t.BAR_PERIOD AS col ,
t.BAR_PRODUCT AS col ,
t.BAR_SCENARIO AS col ,
t.BAR_SHIPTO AS col ,
t.BAR_YEAR AS col ,
t.FISCPER AS col ,
t.ACCT AS col ,
NULL AS col ,
NULL AS col ,
t.QAD_ENTITY AS col ,
t.COSTCTR AS col ,
t.DOCUMENT_TYPE AS col ,
NULL AS col ,
t.DOCUMENT_ID AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.BILL_TO_CUSTOMER AS col ,
t.TRANSACTION_DATE AS col ,
t.QUANTITY AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.SOLD_TO_CUSTOMER AS col ,
t.SITE AS col ,
NULL AS col ,
t.LOADDATETIME AS col ,
t.ID AS col ,
'QAD'AS col ,
b.bar_entity_currency AS col ,
hfm.bar_amt AS col ,
(t.BAR_AMT * hfm.bar_amt * COALESCE (a.flipsign::INTEGER,1)) AS col ,

to_date(GETDATE(),'yyyyMMdd') AS col ,

'etl_user'  FROM   bods.qad_chile_pl_trans_current  t LEFT OUTER JOIN global_pl.bar_acct_attr a ON t.BAR_ACCT = a.bar_account LEFT OUTER JOIN global_pl.bar_entity_attr b ON t.BAR_ENTITY = b.bar_entity LEFT OUTER JOIN bods.hfm_vw_hfm_actual_trans_current hfm ON (t.bar_year = hfm.bar_year AND t.bar_period = hfm.bar_period AND hfm.bar_function = b.bar_entity_currency )
		);		

		(  
			select t.BAR_ACCT AS col ,
t.BAR_AMT AS col ,
t.BAR_BRAND AS col ,
t.BAR_BU AS col ,
t.BAR_CURRTYPE AS col ,
t.BAR_CUSTNO AS col ,
t.BAR_ENTITY AS col ,
t.BAR_FUNCTION AS col ,
t.BAR_PERIOD AS col ,
t.BAR_PRODUCT AS col ,
t.BAR_SCENARIO AS col ,
t.BAR_SHIPTO AS col ,
t.BAR_YEAR AS col ,
t.FISCPER AS col ,
t.ACCT AS col ,
NULL AS col ,
NULL AS col ,
t.QAD_ENTITY AS col ,
t.COSTCTR AS col ,
t.DOCUMENT_TYPE AS col ,
NULL AS col ,
t.DOCUMENT_ID AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.BILL_TO_CUSTOMER AS col ,
t.TRANSACTION_DATE AS col ,
t.QUANTITY AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.SOLD_TO_CUSTOMER AS col ,
t.SITE AS col ,
NULL AS col ,
t.LOADDATETIME AS col ,
t.ID AS col ,
'QAD'AS col ,
b.bar_entity_currency AS col ,
hfm.bar_amt AS col ,
(t.BAR_AMT * hfm.bar_amt * COALESCE (a.flipsign::INTEGER,1)) AS col ,

to_date(GETDATE(),'yyyyMMdd') AS col ,

'etl_user'  FROM   bods.qad_argentina_pl_trans_current  t LEFT OUTER JOIN global_pl.bar_acct_attr a ON t.BAR_ACCT = a.bar_account LEFT OUTER JOIN global_pl.bar_entity_attr b ON t.BAR_ENTITY = b.bar_entity LEFT OUTER JOIN bods.hfm_vw_hfm_actual_trans_current hfm ON (t.bar_year = hfm.bar_year AND t.bar_period = hfm.bar_period AND hfm.bar_function = b.bar_entity_currency )
		);		



		(  
			select t.BAR_ACCT AS col ,
t.BAR_AMT AS col ,
t.BAR_BRAND AS col ,
t.BAR_BU AS col ,
t.BAR_CURRTYPE AS col ,
t.BAR_CUSTNO AS col ,
t.BAR_ENTITY AS col ,
t.BAR_FUNCTION AS col ,
t.BAR_PERIOD AS col ,
t.BAR_PRODUCT AS col ,
t.BAR_SCENARIO AS col ,
t.BAR_SHIPTO AS col ,
t.BAR_YEAR AS col ,
t.FISCPER AS col ,
t.ACCT AS col ,
NULL AS col ,
NULL AS col ,
t.QAD_ENTITY AS col ,
t.COSTCTR AS col ,
t.DOCUMENT_TYPE AS col ,
NULL AS col ,
t.DOCUMENT_ID AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.BILL_TO_CUSTOMER AS col ,
t.TRANSACTION_DATE AS col ,
t.QUANTITY AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.SOLD_TO_CUSTOMER AS col ,
t.SITE AS col ,
NULL AS col ,
t.LOADDATETIME AS col ,
t.ID AS col ,
'QAD'AS col ,
b.bar_entity_currency AS col ,
hfm.bar_amt AS col ,
(t.BAR_AMT * hfm.bar_amt * COALESCE (a.flipsign::INTEGER,1)) AS col ,

to_date(GETDATE(),'yyyyMMdd') AS col ,

'etl_user'  FROM   bods.qad_peru_pl_trans_current  t LEFT OUTER JOIN global_pl.bar_acct_attr a ON t.BAR_ACCT = a.bar_account LEFT OUTER JOIN global_pl.bar_entity_attr b ON t.BAR_ENTITY = b.bar_entity LEFT OUTER JOIN bods.hfm_vw_hfm_actual_trans_current hfm ON (t.bar_year = hfm.bar_year AND t.bar_period = hfm.bar_period AND hfm.bar_function = b.bar_entity_currency )
		);		

		(  
			select t.BAR_ACCT AS col ,
t.BAR_AMT AS col ,
t.BAR_BRAND AS col ,
t.BAR_BU AS col ,
t.BAR_CURRTYPE AS col ,
t.BAR_CUSTNO AS col ,
t.BAR_ENTITY AS col ,
t.BAR_FUNCTION AS col ,
t.BAR_PERIOD AS col ,
t.BAR_PRODUCT AS col ,
t.BAR_SCENARIO AS col ,
NULL AS col ,
t.BAR_YEAR AS col ,
t.FISCPER AS col ,
t.ACCT AS col ,
NULL AS col ,
t.BUS_AREA AS col ,
t.CO_CD AS col ,
t.COST_CNTR AS col ,
t.DOCCT AS col ,
t.DOCLN AS col ,
t.DOCNR AS col ,
REGEXP_REPLACE(SGTXT AS col ,
'[^a-zA-Z0-9\u00E0-\u00FC ]+'AS col ,
'') as SGTXT AS col ,
t.VENDOR_ID AS col ,
t.MATERIAL AS col ,
NULL AS col ,
t.CPUDT AS col ,
t.QUANTITY AS col ,
t.QUANUNIT AS col ,
t.REFDOCCT AS col ,
t.REFDOCLN AS col ,
t.REFDOCNR AS col ,
t.PROFIT_CNTR AS col ,
NULL AS col ,
NULL AS col ,
t.SHIPTO_CUST_NBR AS col ,
NULL AS col ,
t.PLANT AS col ,
t.CHARTACCTS AS col ,
t.LOADDATETIME AS col ,
t.ID AS col ,
'P02'AS col ,
b.bar_entity_currency AS col ,
hfm.bar_amt AS col ,
(t.BAR_AMT * hfm.bar_amt * COALESCE (a.flipsign::INTEGER,1)) AS col ,

to_date(GETDATE(),'yyyyMMdd') AS col ,

'etl_user'  FROM   bods.p02_pl_trans_current  t LEFT OUTER JOIN global_pl.bar_acct_attr a ON t.BAR_ACCT = a.bar_account LEFT OUTER JOIN global_pl.bar_entity_attr b ON t.BAR_ENTITY = b.bar_entity LEFT OUTER JOIN bods.hfm_vw_hfm_actual_trans_current hfm ON (t.bar_year = hfm.bar_year AND t.bar_period = hfm.bar_period AND hfm.bar_function = b.bar_entity_currency )
		);		

		(  
			Select t.BAR_ACCT AS col ,
t.BAR_AMT AS col ,
t.BAR_BRAND AS col ,
t.BAR_BU AS col ,
t.BAR_CURRTYPE AS col ,
t.BAR_CUSTNO AS col ,
t.BAR_ENTITY AS col ,
t.BAR_FUNCTION AS col ,
t.BAR_PERIOD AS col ,
t.BAR_PRODUCT AS col ,
t.BAR_SCENARIO AS col ,
t.BAR_SHIPTO AS col ,
t.BAR_YEAR AS col ,
t.FISCPER AS col ,
t.ACCT AS col ,
NULL AS col ,
NULL AS col ,
t.CO_CD AS col ,
t.COST_CNTR AS col ,
NULL AS col ,
t.DOC_LN_NBR AS col ,
t.DOC_NBR AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.POST_DTE AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.LOADDATETIME AS col ,
t.ID AS col ,
'BAANBESCOTW'AS col ,
b.bar_entity_currency AS col ,
hfm.bar_amt AS col ,
(t.BAR_AMT * hfm.bar_amt * COALESCE (a.flipsign::INTEGER,1)) AS col ,

to_date(GETDATE(),'yyyyMMdd') AS col ,

'etl_user' from bods.baan_besco_tw_pl_trans_current  t LEFT OUTER JOIN global_pl.bar_acct_attr a ON t.BAR_ACCT = a.bar_account LEFT OUTER JOIN global_pl.bar_entity_attr b ON t.BAR_ENTITY = b.bar_entity LEFT OUTER JOIN bods.hfm_vw_hfm_actual_trans_current hfm ON (t.bar_year = hfm.bar_year AND t.bar_period = hfm.bar_period AND hfm.bar_function = b.bar_entity_currency )
		);		


		(  
			select t.BAR_ACCT AS col ,
t.BAR_AMT AS col ,
t.BAR_BRANDAS col ,
t.BAR_BUAS col ,
t.BAR_CURRTYPEAS col ,
t.BAR_CUSTNOAS col ,
t.BAR_ENTITYAS col ,
t.BAR_FUNCTIONAS col ,
t.BAR_PERIODAS col ,
t.BAR_PRODUCTAS col ,
t.BAR_SCENARIOAS col ,
t.BAR_SHIPTOAS col ,
t.BAR_YEARAS col ,
NULLAS col ,
t.ACCTAS col ,
NULLAS col ,
t.FUNCAS col ,
t.ENTITYAS col ,
NULLAS col ,
NULLAS col ,
NULLAS col ,
NULLAS col ,
NULLAS col ,
NULLAS col ,
NULLAS col ,
NULLAS col ,
NULLAS col ,
NULLAS col ,
NULLAS col ,
NULLAS col ,
NULLAS col ,
NULLAS col ,
NULLAS col ,
NULLAS col ,
NULLAS col ,
NULLAS col ,
NULLAS col ,
NULLAS col ,
NULLAS col ,
t.LOADDATETIMEAS col ,
t.ID AS col ,
'NAVISION'AS col ,
b.bar_entity_currency AS col ,
hfm.bar_amt AS col ,
(t.BAR_AMT * hfm.bar_amt * COALESCE (a.flipsign::INTEGER,1)) AS col ,

to_date(GETDATE(),'yyyyMMdd') AS col ,

 'etl_user'  FROM   bods.navision_actuals_trans_current  t LEFT OUTER JOIN global_pl.bar_acct_attr a ON t.BAR_ACCT = a.bar_account LEFT OUTER JOIN global_pl.bar_entity_attr b ON t.BAR_ENTITY = b.bar_entity LEFT OUTER JOIN bods.hfm_vw_hfm_actual_trans_current hfm ON (t.bar_year = hfm.bar_year AND t.bar_period = hfm.bar_period AND hfm.bar_function = b.bar_entity_currency )
		);		

		(  
			select t.BAR_ACCT AS col ,
t.BAR_AMT AS col ,
t.BAR_BRAND AS col ,
t.BAR_BU AS col ,
t.BAR_CURRTYPE AS col ,
t.BAR_CUSTNO AS col ,
t.BAR_ENTITY AS col ,
t.BAR_FUNCTION AS col ,
t.BAR_PERIOD AS col ,
t.BAR_PRODUCT AS col ,
t.BAR_SCENARIO AS col ,
t.BAR_SHIPTO AS col ,
t.BAR_YEAR AS col ,
t.FISCPER AS col ,
t.ACCOUNT AS col ,
t.BRAND AS col ,
NULL AS col ,
t.ENTITY AS col ,
NULL AS col ,
t.DOCUMENT_TYPE AS col ,
NULL AS col ,
t.DOCUMENT_ID AS col ,
NULL AS col ,
NULL AS col ,
t.PRODUCT AS col ,
t.CUSTOMER AS col ,
t.POSTING_DATE AS col ,
t.QUANTITY AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.COMPANY AS col ,
NULL AS col ,
NULL AS col ,
t.END_CUSTOMER AS col ,
t.SOLD_TO_CUSTOMER AS col ,
t.PLANT AS col ,
NULL AS col ,
t.LOADDATETIME AS col ,
t.ID AS col ,
'JDE'AS col ,
b.bar_entity_currency AS col ,
hfm.bar_amt AS col ,
(t.BAR_AMT * hfm.bar_amt * COALESCE (a.flipsign::INTEGER,1)) AS col ,

to_date(GETDATE(),'yyyyMMdd') AS col ,

'etl_user'  FROM   bods.jde_na_pl_trans_current  t LEFT OUTER JOIN global_pl.bar_acct_attr a ON t.BAR_ACCT = a.bar_account LEFT OUTER JOIN global_pl.bar_entity_attr b ON t.BAR_ENTITY = b.bar_entity LEFT OUTER JOIN bods.hfm_vw_hfm_actual_trans_current hfm ON (t.bar_year = hfm.bar_year AND t.bar_period = hfm.bar_period AND hfm.bar_function = b.bar_entity_currency )
		);		


		(  
			Select t.BAR_ACCT AS col ,
t.BAR_AMT AS col ,
t.BAR_BRAND AS col ,
t.BAR_BU AS col ,
t.BAR_CURRTYPE AS col ,
t.BAR_CUSTNO AS col ,
t.BAR_ENTITY AS col ,
t.BAR_FUNCTION AS col ,
t.BAR_PERIOD AS col ,
t.BAR_PRODUCT AS col ,
t.BAR_SCENARIO AS col ,
t.BAR_SHIPTO AS col ,
t.BAR_YEAR AS col ,
t.FISCPER AS col ,
t.ACCT AS col ,
NULL AS col ,
t.ICP_CD AS col ,
t.CO_CD AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.TXN_ID AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.POST_DTE AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
NULL AS col ,
t.LOADDATETIME AS col ,
t.ID AS col ,
'ORCHPPE'AS col ,
b.bar_entity_currency AS col ,
hfm.bar_amt AS col ,
(t.BAR_AMT * hfm.bar_amt * COALESCE (a.flipsign::INTEGER,1)) AS col ,

to_date(GETDATE(),'yyyyMMdd') AS col ,

'etl_user'   FROM bods.orch_ppe_pl_trans_current  t LEFT OUTER JOIN global_pl.bar_acct_attr a ON t.BAR_ACCT = a.bar_account LEFT OUTER JOIN global_pl.bar_entity_attr b ON t.BAR_ENTITY = b.bar_entity LEFT OUTER JOIN bods.hfm_vw_hfm_actual_trans_current hfm ON (t.bar_year = hfm.bar_year AND t.bar_period = hfm.bar_period AND hfm.bar_function = b.bar_entity_currency )
		);		