version: 2

sources:
  - name: bods
    database: RAW
    tables:
      - name: c11_0ec_pca3
      - name: c11_0material_attr
      - name: drm_entity
      - name: hfm_vw_hfm_actual_trans
      - name: lawson_mac_pl_trans
      - name: p10_0ec_pca_3_trans

  - name: ref_data
    database: RAW
    tables:
      - name: hfmfxrates
      - name: p_build_hfmfxrates

  - name: sapc11
    database: RAW
    tables:
      - name: mara
      - name: t023t

  - name: sftpgtsi
    database: RAW
    tables:
      - name: rsabible
