
CREATE OR REPLACE PROCEDURE dw.p_build_dim_date(flag_reload integer)
 LANGUAGE plpgsql
AS $$ 
Begin 
	
	/* This table does not use identity based surrogate key, so does not need Insert / Update Strategy */
	
	/* check for full reload */
	if(flag_reload = 1)
	then
		delete from dw.dim_date;
	end if;
	

	delete from dw.dim_date;
	INSERT INTO dw.dim_date (
				dy_id,
				dy_dte,
				absolute_dy_nbr,
				absolute_wk_nbr,
				absolute_mth_nbr,
				absolute_qtr_nbr,
				dy_in_wk_nbr,
				dy_in_wk_name,
				julian_dy_nbr,
				clndr_wk_nbr,
				clndr_wk_id,
				clndr_mth_nbr,
				clndr_mth_id,
				clndr_mth_name,
				clndr_qtr_nbr,
				clndr_qtr_id,
				clndr_qtr_name,
				clndr_yr_id,
				clndr_dy_in_mth_nbr,
				is_first_dy_in_clndr_mth_flag,
				is_last_dy_in_clndr_mth_flag,
				wk_begin_dte,
				wk_end_dte,
				fmth_begin_dte,
				fmth_end_dte,
				fqtr_begin_dte,
				fqtr_end_dte,
				fyr_begin_dte,
				fyr_end_dte,
				fwk_nbr,
				fwk_id,
				fwk_cd,
				fmth_nbr,
				fmth_id,
				fmth_cd,
				fmth_name,
				fmth_short_name,
				fqtr_nbr,
				fqtr_id,
				fqtr_cd,
				fqtr_name,
				fyr_id,
				fdy_in_mth_nbr,
				fscl_days_remaining_in_mth,
				fdy_in_qtr_nbr,
				fscl_days_remaining_in_qtr,
				fdy_in_yr_nbr,
				fscl_days_remaining_in_yr,
				fwk_in_mth_nbr,
				fwk_in_qtr,
				is_wk_dy_flag,
				is_weekend_flag,
				is_first_dy_of_fwk_flag,
				is_last_dy_of_fwk_flag,
				is_first_dy_of_fmth_flag,
				is_last_dy_of_fmth_flag,
				is_first_dy_of_fqtr_flag,
				is_last_dy_of_fqtr_flag,
				is_first_dy_of_fyr_flag,
				is_last_dy_of_fyr_flag,
				season_name,
				holiday_name,
				holiday_season_name,
				holiday_observed_name,
				special_event_name
	
		)
		SELECT	dy_id,
				dy_dte,
				absolute_dy_nbr,
				absolute_wk_nbr,
				absolute_mth_nbr,
				absolute_qtr_nbr,
				dy_in_wk_nbr,
				dy_in_wk_name,
				julian_dy_nbr,
				clndr_wk_nbr,
				clndr_wk_id,
				clndr_mth_nbr,
				clndr_mth_id,
				clndr_mth_name,
				clndr_qtr_nbr,
				clndr_qtr_id,
				clndr_qtr_name,
				clndr_yr_id,
				clndr_dy_in_mth_nbr,
				is_first_dy_in_clndr_mth_flag,
				is_last_dy_in_clndr_mth_flag,
				wk_begin_dte,
				wk_end_dte,
				fmth_begin_dte,
				fmth_end_dte,
				fqtr_begin_dte,
				fqtr_end_dte,
				fyr_begin_dte,
				fyr_end_dte,
				fwk_nbr,
				fwk_id,
				fwk_cd,
				fmth_nbr,
				fmth_id,
				fmth_cd,
				fmth_name,
				fmth_short_name,
				fqtr_nbr,
				fqtr_id,
				fqtr_cd,
				fqtr_name,
				fyr_id,
				fdy_in_mth_nbr,
				fscl_days_remaining_in_mth,
				fdy_in_qtr_nbr,
				fscl_days_remaining_in_qtr,
				fdy_in_yr_nbr,
				fscl_days_remaining_in_yr,
				fwk_in_mth_nbr,
				fwk_in_qtr,
				is_wk_dy_flag,
				is_weekend_flag,
				is_first_dy_of_fwk_flag,
				is_last_dy_of_fwk_flag,
				is_first_dy_of_fmth_flag,
				is_last_dy_of_fmth_flag,
				is_first_dy_of_fqtr_flag,
				is_last_dy_of_fqtr_flag,
				is_first_dy_of_fyr_flag,
				is_last_dy_of_fyr_flag,
				season_name,
				holiday_name,
				holiday_season_name,
				holiday_observed_name,
				special_event_name
		FROM 	ref_data.calendar
	;

exception
when others then raise info 'exception occur while ingesting data in dim_date';
END 
$$
;