REATE OR REPLACE PROCEDURE otif.edw_shipments_mod1(i_schema_name varchar)
	LANGUAGE plpgsql
AS $$
	
	
	
	
	
	
declare
	v_schema_name character varying(32);
	v_job_name varchar(100);
    v_table_name varchar(100);
    v_source_system varchar(50);
	v_job_id int;
	v_exit_code int;
    v_runid int;
	v_start_timestamp timestamp;
	v_endtimestamp timestamp;
    v_insertcount bigint;
    v_integer_var bigint;
    v_totalcount bigint;
    v_deletecount bigint;
    audit_rec RECORD;
	v_last_extract_timestamp timestamp;
begin
	v_schema_name := upper(i_schema_name);
	v_job_id=19;
	SELECT INTO audit_rec * FROM EDW.EDW_STAGE.job_master WHERE job_id = v_job_id;
	v_start_timestamp:=(select current_timestamp);
	v_source_system=audit_rec.source_sys;
	v_job_name=audit_rec.job_name;
    v_table_name=audit_rec.table_name;
    v_runid=(select pg_backend_pid());
	v_last_extract_timestamp=audit_rec.last_extract_timestamp;
	v_exit_code=-1;
     
	--truncate edw.otif.edw_shipments;
	execute ('delete from edw.otif.edw_shipments where source_schema = '''||v_schema_name||''';');
	execute ( 'insert into edw.otif.edw_shipments
	(
	 source_schema,
	 order_number, 
	 order_class, 
	 order_status, 
	 cancelled, 
	 ship_complete, 
	 order_window, 
	 ctrl_user_id, 
	 ctrl_dt, 
	 delivery_appt_reqd, 
	 special_label_flag, 
	 single_pack_flag, 
	 pack_slip_sort_by, 
	 pack_slip_qty, 
	 pack_slip_handling, 
	 pallet_pack_slip, 
	 repack_pack_slip, 
	 bol_number, 
	 scac, 
	 carrier_class, 
	 load_id, 
	 cancel_type, 
	 wave_dt, 
	 wave_number, 
	 depart_dt, 
	 completion_dt, 
	 resultant_sku, 
	 expected_qty, 
	 account_code, 
	 early_delivery_dt, 
	 exclusion_start_dt, 
	 exclusion_end_dt, 
	 contact_name, 
	 contact_phone, 
	 appt_notice_hours, 
	 customer_number, 
	 sold_to_name, 
	 retail_store_number,
	 chain_number, 
	 dept_number, 
	 po_number, 
	 cancel_by_dt, 
	 freight_allowed_cd, 
	 custom_pallet_number, 
	 pack_slip_fax, 
	 receiving_from_tm, 
	 receiving_to_tm, 
	 address1, 
	 address2, 
	 address3, 
	 address4, 
	 zip_code, 
	 freight_cost_tot, 
	 tariff_used, 
	 tariff_category,
	 manifest_number, 
	 shipping_zone_code, 
	 order_entry_dt, 
	 bundling_slot, 
	 business_unit, 
	 combination_group, 
	 pallet_override, 
	 like_product_flag, 
	 full_pallet_flag, 
	 appt_number, 
	 appt_dt, 
	 cust_order_type, 
	 ship_or_cancel_flag,
	 sap_delivery, 
	 sap_delivery_type, 
	 sap_plant, 
	 sap_route, 
	 sap_createdondate, 
	 sap_createdontime, 
	 sap_plandate, 
	 sap_pickingdate, 
	 sap_loadingdate, 
	 sap_deliverydate, 
	 sap_transpdate, 
	 sap_actgoodsissue, 
	 sap_order, 
	 line_number, 
	 sku, 
	 top_level_flag, 
	 optimize_flag, 
	 inventory_item, 
	 order_type, 
	 order_qty, 
	 allocated_qty, 
	 picked_qty, 
	 od_ctrl_user_id, 
	 od_ctrl_dt, 
	 status_cd, 
	 starting_date_code, 
	 ending_date_code, 
	 freight_group_cd, 
	 customer_sku, 
	 backorder_qty, 
	 cancelled_qty, 
	 customer_retail_price, 
	 committed_qty, 
	 unit_gsv, 
	 committed_unit_gsv, 
	 pi_code, 
	 wo_use_qty, 
	 pick_conv_as_nonconv, 
	 wo_comp_units, 
	 sales_order_flag, 
	 description, 
	 product_type_code, 
	 pallet_config_id, 
	 pallet_config_qty, 
	 plan_uom, 
	 customer_line_number, 
	 sp_loc, 
	 customer_material_desc, 
	 inner_pack_qty, 
	 outer_pack_qty, 
	 customer_putaway_location, 
	 chase_flag, 
	 material_availability_date, 
	 customers_customer_item_number, 
	 unit_gsv_per, 
	 unit_price_per, 
	 component_line_number, 
	 orig_committed_qty, 
	 work_order_number, 
	 mto_weight, 
	 mto_cube, 
	 orig_chase_flag, 
	 multiply_divide_ind,
	 multiply_divide_qty, 
	 facility_number, 
	 po_type, 
	 planned_dt, 
	 staged_dt, 
	 loaded_dt, 
	 documented_dt, 
	 ptp_released_dt, 
	 ptp_first_picked_dt, 
	 ptp_last_picked_dt,
	 ptp_first_palletize_dt,
	 ptp_last_palletize_dt,
	 ptp_first_staged_dt, 
	 ptp_last_staged_dt,
	 ptp_first_loaded_dt,
	 ptp_last_loaded_dt, 
	 plt_released_dt, 
	 plt_first_picked_dt, 
	 plt_last_picked_dt, 
	 plt_first_palletize_dt, 
	 plt_last_palletize_dt, 
	 plt_first_staged_dt, 
	 plt_last_staged_dt, 
	 plt_first_loaded_dt,
	 plt_last_loaded_dt, 
	 rpk_released_dt, 
	 rpk_first_picked_dt, 
	 rpk_last_picked_dt, 
	 rpk_first_sealed_dt, 
	 rpk_last_sealed_dt, 
	 rpk_first_prim_comp_dt, 
	 rpk_last_prim_comp_dt, 
	 ptb_released_dt, 
	 ptb_first_picked_dt, 
	 ptb_last_picked_dt, 
	 ptb_first_prim_comp_dt,
	 ptb_last_prim_comp_dt, 
	 cnv_first_assign_dt, 
	 cnv_last_assign_dt, 
	 cnv_first_sec_comp_dt, 
	 cnv_last_sec_comp_dt, 
	 cnv_first_palletize_dt, 
	 cnv_last_palletize_dt,
	 cnv_first_staged_dt, 
	 cnv_last_staged_dt, 
	 cnv_first_loaded_dt, 
	 cnv_last_loaded_dt, 
	 first_bundled_dt, 
	 last_bundled_dt, 
	 first_pallet_specials_in_dt, 
	 last_pallet_specials_in_dt, 
	 first_pallet_specials_out_dt, 
	 last_pallet_specials_out_dt, 
	 consign_to_id, load_status,
	 live_load_flag, 
	 trans_mode, 
	 trailer_type, 
	 lc_scac, 
	 number_stops, 
	 lc_depart_dt, 
	 lc_ctrl_user_id, 
	 lc_ctrl_dt, 
	 lc_bol_number, 
	 trailer_id, 
	 pro_number, 
	 seal_number, 
	 insert_dt, 
	 first_plan_dt, 
	 last_plan_dt, 
	 lc_loaded_dt,
	 sealed_dt, 
	 lc_documented_dt, 
	 lc_completion_dt, 
	 originating_supplier, 
	 co_load_id, 
	 staging_location, 
	 specials_location, 
	 left_right, 
	 first_wave_dt, 
	 first_wave_number, 
	 last_wave_dt, 
	 last_wave_number, 
	 transfer_load_flag, 
	 transfer_scac, 
	 transfer_in_flag, 
	 trailer_checkout_flag, 
	 reported, switch_load_flag,
	 building_number, 
	 cust_load_ref, 
	 auto_planned_flag, 
	 planned_pickup_dt, 
	 original_pickup_dt, 
	 pickup_reason_code, 
	 lc_facility_number, 
	 customer_code, 
	 lc_address1, 
	 lc_address2, 
	 lc_address3, 
	 lc_address4, 
	 lc_zip_code,
	 comments, 
	 dangerous_goods_placard, 
	 planned_notif_dt, 
	 documented_notif_dt, 
	 staging_assign_user_id, 
	 staging_assign_ctrl_dt,
	 pallet_count, 
	 proforma_invoice_sent, 
	 proforma_invoice_sent_dt, 
	 load_signed, 
	 load_signed_dt, 
	 carrier_name,
	 etl_crte_user,
	 etl_crte_ts	 
	 )
	
	(
			 select '''||v_schema_name||''',
			oh.ORDER_NUMBER,
			oh.ORDER_CLASS,
			oh.ORDER_STATUS,
			oh.CANCELLED,
			oh.SHIP_COMPLETE,
			oh.ORDER_WINDOW,
			oh.CTRL_USER_ID,
			oh.CTRL_DT,
			oh.DELIVERY_APPT_REQD,
			oh.SPECIAL_LABEL_FLAG,
			oh.SINGLE_PACK_FLAG,
			oh.PACK_SLIP_SORT_BY,
			oh.PACK_SLIP_QTY,
			oh.PACK_SLIP_HANDLING,
			oh.PALLET_PACK_SLIP,
			oh.REPACK_PACK_SLIP,
			oh.BOL_NUMBER,
			oh.SCAC,
			oh.CARRIER_CLASS,
			oh.LOAD_ID,
			oh.CANCEL_TYPE,
			oh.WAVE_DT,
			oh.WAVE_NUMBER,
			oh.DEPART_DT,
			oh.COMPLETION_DT,
			oh.RESULTANT_SKU,
			oh.EXPECTED_QTY,
			oh.ACCOUNT_CODE,
			oh.EARLY_DELIVERY_DT,
			oh.EXCLUSION_START_DT,
			oh.EXCLUSION_END_DT,
			oh.CONTACT_NAME,
			oh.CONTACT_PHONE,
			oh.APPT_NOTICE_HOURS,
			oh.CUSTOMER_NUMBER,
			oh.SOLD_TO_NAME,
			oh.RETAIL_STORE_NUMBER,
			oh.CHAIN_NUMBER,
			oh.DEPT_NUMBER,
			oh.PO_NUMBER,
			oh.CANCEL_BY_DT,
			oh.FREIGHT_ALLOWED_CD,
			oh.CUSTOM_PALLET_NUMBER,
			oh.PACK_SLIP_FAX,
			oh.RECEIVING_FROM_TM,
			oh.RECEIVING_TO_TM,
			oh.ADDRESS1,
			oh.ADDRESS2,
			oh.ADDRESS3,
			oh.ADDRESS4,
			oh.ZIP_CODE,
			oh.FREIGHT_COST_TOT,
			oh.TARIFF_USED,
			oh.TARIFF_CATEGORY,
			oh.MANIFEST_NUMBER,
			oh.SHIPPING_ZONE_CODE,
			oh.ORDER_ENTRY_DT,
			oh.BUNDLING_SLOT,
			oh.BUSINESS_UNIT,
			oh.COMBINATION_GROUP,
			oh.PALLET_OVERRIDE,
			oh.LIKE_PRODUCT_FLAG,
			oh.FULL_PALLET_FLAG,
			oh.APPT_NUMBER,
			oh.APPT_DT,
			oh.CUST_ORDER_TYPE,
			oh.SHIP_OR_CANCEL_FLAG,
			lip.vbeln as sap_delivery,
			lip.lfart as sap_delivery_type,
			lip.werks  as sap_plant,
			lip.route  as sap_route,
			lip.erdat  as sap_createdondate,
			lip.erzet as sap_createdontime,
			lip.wadat as sap_plandate,
			lip.kodat as sap_pickingdate,
			lip.lddat as sap_loadingdate,
			lip.lfdat as sap_deliverydate,
			lip.tddat as sap_transpdate,
			lip.wadat_ist as sap_actgoodsissue,
			null as sap_order,
			--od.ORDER_NUMBER,
			od.LINE_NUMBER,
			od.SKU,
			od.TOP_LEVEL_FLAG,
			od.OPTIMIZE_FLAG,
			od.INVENTORY_ITEM,
			od.ORDER_TYPE,
			od.ORDER_QTY,
			od.ALLOCATED_QTY,
			od.PICKED_QTY,
			od.CTRL_USER_ID,
			od.CTRL_DT,
			od.STATUS_CD,
			od.STARTING_DATE_CODE,
			od.ENDING_DATE_CODE,
			od.FREIGHT_GROUP_CD,
			od.CUSTOMER_SKU,
			od.BACKORDER_QTY,
			od.CANCELLED_QTY,
			od.CUSTOMER_RETAIL_PRICE,
			od.COMMITTED_QTY,
			od.UNIT_GSV,
			od.COMMITTED_UNIT_GSV,
			od.PI_CODE,
			od.WO_USE_QTY,
			od.PICK_CONV_AS_NONCONV,
			od.WO_COMP_UNITS,
			od.SALES_ORDER_FLAG,
			od.DESCRIPTION,
			od.PRODUCT_TYPE_CODE,
			od.PALLET_CONFIG_ID,
			od.PALLET_CONFIG_QTY,
			od.PLAN_UOM,
			od.CUSTOMER_LINE_NUMBER,
			od.SP_LOC,
			od.CUSTOMER_MATERIAL_DESC,
			od.INNER_PACK_QTY,
			od.OUTER_PACK_QTY,
			od.CUSTOMER_PUTAWAY_LOCATION,
			od.CHASE_FLAG,
			od.MATERIAL_AVAILABILITY_DATE,
			od.CUSTOMERS_CUSTOMER_ITEM_NUMBER,
			od.UNIT_GSV_PER,
			od.UNIT_PRICE_PER,
			od.COMPONENT_LINE_NUMBER,
			od.ORIG_COMMITTED_QTY,
			od.WORK_ORDER_NUMBER,
			od.MTO_WEIGHT,
			od.MTO_CUBE,
			od.ORIG_CHASE_FLAG,
			od.MULTIPLY_DIVIDE_IND,
			od.MULTIPLY_DIVIDE_QTY,
			--odt.ORDER_NUMBER,
			odt.FACILITY_NUMBER,
			odt.PO_TYPE,
			odt.PLANNED_DT,
			odt.STAGED_DT,
			odt.LOADED_DT,
			odt.DOCUMENTED_DT,
			odt.PTP_RELEASED_DT,
			odt.PTP_FIRST_PICKED_DT,
			odt.PTP_LAST_PICKED_DT,
			odt.PTP_FIRST_PALLETIZE_DT,
			odt.PTP_LAST_PALLETIZE_DT,
			odt.PTP_FIRST_STAGED_DT,
			odt.PTP_LAST_STAGED_DT,
			odt.PTP_FIRST_LOADED_DT,
			odt.PTP_LAST_LOADED_DT,
			odt.PLT_RELEASED_DT,
			odt.PLT_FIRST_PICKED_DT,
			odt.PLT_LAST_PICKED_DT,
			odt.PLT_FIRST_PALLETIZE_DT,
			odt.PLT_LAST_PALLETIZE_DT,
			odt.PLT_FIRST_STAGED_DT,
			odt.PLT_LAST_STAGED_DT,
			odt.PLT_FIRST_LOADED_DT,
			odt.PLT_LAST_LOADED_DT,
			odt.RPK_RELEASED_DT,
			odt.RPK_FIRST_PICKED_DT,
			odt.RPK_LAST_PICKED_DT,
			odt.RPK_FIRST_SEALED_DT,
			odt.RPK_LAST_SEALED_DT,
			odt.RPK_FIRST_PRIM_COMP_DT,
			odt.RPK_LAST_PRIM_COMP_DT,
			odt.PTB_RELEASED_DT,
			odt.PTB_FIRST_PICKED_DT,
			odt.PTB_LAST_PICKED_DT,
			odt.PTB_FIRST_PRIM_COMP_DT,
			odt.PTB_LAST_PRIM_COMP_DT,
			odt.CNV_FIRST_ASSIGN_DT,
			odt.CNV_LAST_ASSIGN_DT,
			odt.CNV_FIRST_SEC_COMP_DT,
			odt.CNV_LAST_SEC_COMP_DT,
			odt.CNV_FIRST_PALLETIZE_DT,
			odt.CNV_LAST_PALLETIZE_DT,
			odt.CNV_FIRST_STAGED_DT,
			odt.CNV_LAST_STAGED_DT,
			odt.CNV_FIRST_LOADED_DT,
			odt.CNV_LAST_LOADED_DT,
			odt.FIRST_BUNDLED_DT,
			odt.LAST_BUNDLED_DT,
			odt.FIRST_PALLET_SPECIALS_IN_DT,
			odt.LAST_PALLET_SPECIALS_IN_DT,
			odt.FIRST_PALLET_SPECIALS_OUT_DT,
			odt.LAST_PALLET_SPECIALS_OUT_DT,
			odt.CONSIGN_TO_ID,
			--lc.LOAD_ID,
			lc.LOAD_STATUS,
			lc.LIVE_LOAD_FLAG,
			lc.TRANS_MODE,
			lc.TRAILER_TYPE,
			lc.SCAC,
			lc.NUMBER_STOPS,
			lc.DEPART_DT,
			lc.CTRL_USER_ID,
			lc.CTRL_DT,
			lc.BOL_NUMBER,
			lc.TRAILER_ID,
			lc.PRO_NUMBER,
			lc.SEAL_NUMBER,
			lc.INSERT_DT,
			lc.FIRST_PLAN_DT,
			lc.LAST_PLAN_DT,
			lc.LOADED_DT,
			lc.SEALED_DT,
			lc.DOCUMENTED_DT,
			lc.COMPLETION_DT,
			lc.ORIGINATING_SUPPLIER,
			lc.CO_LOAD_ID,
			lc.STAGING_LOCATION,
			lc.SPECIALS_LOCATION,
			lc.LEFT_RIGHT,
			lc.FIRST_WAVE_DT,
			lc.FIRST_WAVE_NUMBER,
			lc.LAST_WAVE_DT,
			lc.LAST_WAVE_NUMBER,
			lc.TRANSFER_LOAD_FLAG,
			lc.TRANSFER_SCAC,
			lc.TRANSFER_IN_FLAG,
			lc.TRAILER_CHECKOUT_FLAG,
			lc.REPORTED,
			lc.SWITCH_LOAD_FLAG,
			lc.BUILDING_NUMBER,
			lc.CUST_LOAD_REF,
			lc.AUTO_PLANNED_FLAG,
			lc.PLANNED_PICKUP_DT,
			lc.ORIGINAL_PICKUP_DT,
			lc.PICKUP_REASON_CODE,
			lc.FACILITY_NUMBER,
			lc.CUSTOMER_CODE,
			lc.ADDRESS1,
			lc.ADDRESS2,
			lc.ADDRESS3,
			lc.ADDRESS4,
			lc.ZIP_CODE,
			lc.COMMENTS,
			lc.DANGEROUS_GOODS_PLACARD,
			lc.PLANNED_NOTIF_DT,
			lc.DOCUMENTED_NOTIF_DT,
			lc.STAGING_ASSIGN_USER_ID,
			lc.STAGING_ASSIGN_CTRL_DT,
			lc.PALLET_COUNT,
			lc.PROFORMA_INVOICE_SENT,
			lc.PROFORMA_INVOICE_SENT_DT,
			lc.LOAD_SIGNED,
			lc.LOAD_SIGNED_DT,
			lc.CARRIER_NAME,
			''ETL_USER'' as etl_crte_user,
			current_timestamp etl_crte_ts
		from '||v_schema_name||'.orderheader_current oh
		left join '||v_schema_name||'.orderdetail_current od 
		  on oh.order_number = od.order_number 
		inner join '||v_schema_name||'.orderdates_current odt
		  on odt.order_number = oh.order_number 
		inner join '||v_schema_name||'.load_current lc
		  on oh.load_id = lc.load_id
		left join  sapc11.likp_current lip
     	  on lpad(substring(oh.order_number,4,15),10,''0'') = lip.vbeln 
--		left join sapc11.lips_current lis
--		  on lpad(substring(oh.order_number,4,15),10,''0'') = lis.vbeln
	)'
	);

	v_endtimestamp:=(select current_timestamp);
    GET DIAGNOSTICS v_integer_var:= ROW_COUNT;
	RAISE NOTICE 'INSERTED RECORDS INTO % %; RECORD COUNT:%', v_source_system, v_table_name, v_integer_var;
	v_exit_code=0;	

	update edw.edw_stage.job_master
	set job_state=case when v_exit_code=0 then 'SUCCESS' ELSE 'FAILED' end,
	last_extract_timestamp=current_timestamp,
	etl_updt_ts=current_timestamp
	where job_id=v_job_id;
	RAISE NOTICE 'RECORD UPDATED IN JOB_MASTER';

    update EDW.EDW_STAGE.job_history
	set job_status=case when v_exit_code=0 then 'SUCCESS' ELSE 'FAILED' end,
	end_timestamp=v_endtimestamp,
	etl_updt_ts=current_timestamp,
	insert_count=v_integer_var,
	update_count=0,
	delete_count=0
	--total_count=v_integer_var
	where run_id=v_runid;
    RAISE NOTICE 'RECORD UPDATED IN JOB_HISTORY';
    RAISE NOTICE 'INCREMENTAL LOAD FOR % % COMPLETED SUCCESSFULLY', v_source_system, v_table_name;

        
end;

$$
;