{% set table_metadata = { 
	 "table_definition":" 
		CREATE TABLE IF NOT EXISTS global_pl.calendar
(
	dy_id NUMERIC(18,0)   
	,dy_dte TIMESTAMP WITHOUT TIME ZONE   
	,absolute_dy_nbr NUMERIC(18,0)   
	,absolute_wk_nbr NUMERIC(18,0)   
	,absolute_mth_nbr NUMERIC(18,0)   
	,absolute_qtr_nbr NUMERIC(18,0)   
	,dy_in_wk_nbr NUMERIC(18,0)   
	,dy_in_wk_name VARCHAR(256)   
	,julian_dy_nbr NUMERIC(18,0)   
	,clndr_wk_nbr NUMERIC(18,0)   
	,clndr_wk_id NUMERIC(18,0)   
	,clndr_mth_nbr NUMERIC(18,0)   
	,clndr_mth_id VARCHAR(256)   
	,clndr_mth_name VARCHAR(256)   
	,clndr_qtr_nbr NUMERIC(18,0)   
	,clndr_qtr_id VARCHAR(256)   
	,clndr_qtr_name VARCHAR(256)   
	,clndr_yr_id NUMERIC(18,0)   
	,clndr_dy_in_mth_nbr NUMERIC(18,0)   
	,is_first_dy_in_clndr_mth_flag VARCHAR(256)   
	,is_last_dy_in_clndr_mth_flag VARCHAR(256)   
	,wk_begin_dte TIMESTAMP WITHOUT TIME ZONE   
	,wk_end_dte NUMERIC(18,0)   
	,fmth_begin_dte NUMERIC(18,0)   
	,fmth_end_dte NUMERIC(18,0)   
	,fqtr_begin_dte NUMERIC(18,0)   
	,fqtr_end_dte NUMERIC(18,0)   
	,fyr_begin_dte NUMERIC(18,0)   
	,fyr_end_dte NUMERIC(18,0)   
	,fwk_nbr NUMERIC(18,0)   
	,fwk_id NUMERIC(18,0)   
	,fwk_cd VARCHAR(256)   
	,fmth_nbr NUMERIC(18,0)   
	,fmth_id NUMERIC(18,0)   
	,fmth_cd VARCHAR(256)   
	,fmth_name VARCHAR(256)   
	,fmth_short_name VARCHAR(256)   
	,fqtr_nbr NUMERIC(18,0)   
	,fqtr_id NUMERIC(18,0)   
	,fqtr_cd VARCHAR(256)   
	,fqtr_name VARCHAR(256)   
	,fyr_id NUMERIC(18,0)   
	,fdy_in_mth_nbr NUMERIC(18,0)   
	,fscl_days_remaining_in_mth NUMERIC(18,0)   
	,fdy_in_qtr_nbr NUMERIC(18,0)   
	,fscl_days_remaining_in_qtr NUMERIC(18,0)   
	,fdy_in_yr_nbr NUMERIC(18,0)   
	,fscl_days_remaining_in_yr NUMERIC(18,0)   
	,fwk_in_mth_nbr NUMERIC(18,0)   
	,fwk_in_qtr NUMERIC(18,0)   
	,is_wk_dy_flag VARCHAR(256)   
	,is_weekend_flag VARCHAR(256)   
	,is_first_dy_of_fwk_flag VARCHAR(256)   
	,is_last_dy_of_fwk_flag VARCHAR(256)   
	,is_first_dy_of_fmth_flag VARCHAR(256)   
	,is_last_dy_of_fmth_flag VARCHAR(256)   
	,is_first_dy_of_fqtr_flag VARCHAR(256)   
	,is_last_dy_of_fqtr_flag VARCHAR(256)   
	,is_first_dy_of_fyr_flag VARCHAR(256)   
	,is_last_dy_of_fyr_flag VARCHAR(256)   
	,season_name VARCHAR(256)   
	,holiday_name VARCHAR(256)   
	,holiday_season_name VARCHAR(256)   
	,holiday_observed_name VARCHAR(256)   
	,special_event_name VARCHAR(256)   
	,etl_batch_id NUMERIC(18,0)   
) 
	"
}%} 

{{ config(materialized = "ephemeral") }}
{% do run_query(table_metadata.table_definition) %}