version: 2

sources:
  - name: SAP_E03
    database: DEV_RAW
    schema: SAPE03 
    tables:
      - name: VW_VBAP
      - name: VW_VBAK
      - name: VW_VBPA
      - name: VW_VBUK
      - name: VW_VBUP
      - name: VW_LIPS
      - name: VW_LIKP
      - name: VW_VBRP
      - name: VW_VBRK
      - name: VW_T001W
      - name: VW_MAKT
      - name: VW_MARA
      - name: VW_MARC
      - name: VW_KNVH
      - name: VW_KNA1
      - name: VW_KNVV
      - name: VW_T001
      - name: VW_TVTW
      - name: VW_TSPAT
      - name: VW_TSPA
      - name: VW_TVKO
      - name: VW_THIT
      - name: VW_VBAP_CHANGES
      - name: VW_VBAK_CHANGES
      - name: VW_VBPA_CHANGES
      - name: VW_VBUK_CHANGES
      - name: VW_VBUP_CHANGES
      - name: VW_LIPS_CHANGES
      - name: VW_LIKP_CHANGES
      - name: VW_VBRP_CHANGES
      - name: VW_VBRK_CHANGES
      - name: VW_T001W_CHANGES
      - name: VW_MAKT_CHANGES
      - name: VW_MARA_CHANGES
      - name: VW_MARC_CHANGES
      - name: VW_KNVH_CHANGES
      - name: VW_KNA1_CHANGES
      - name: VW_KNVV_CHANGES
      - name: VW_T001_CHANGES
      - name: VW_TVTW_CHANGES
      - name: VW_TSPAT_CHANGES
      - name: VW_TSPA_CHANGES
      - name: VW_TVKO_CHANGES
      - name: VW_THIT_CHANGES
      - name: VBAP
      - name: VBAK
      - name: VBPA
      - name: VBUK
      - name: VBUP
      - name: LIPS
      - name: LIKP
      - name: VBRP
      - name: VBRK
      - name: T001W
      - name: MAKT
      - name: MARA
      - name: MARC
      - name: KNVH
      - name: KNA1
      - name: KNVV
      - name: T001
      - name: TVTW
      - name: TSPAT
      - name: TSPA
      - name: TVKO
      - name: THIT
      - name: VBAP_CT
      - name: VBAK_CT
      - name: VBPA_CT
      - name: VBUK_CT
      - name: VBUP_CT
      - name: LIPS_CT
      - name: LIKP_CT
      - name: VBRP_CT
      - name: VBRK_CT
      - name: T001W_CT
      - name: MAKT_CT
      - name: MARA_CT
      - name: MARC_CT
      - name: KNVH_CT
      - name: KNA1_CT
      - name: KNVV_CT
      - name: T001_CT
      - name: TVTW_CT
      - name: TSPAT_CT
      - name: TSPA_CT
      - name: TVKO_CT
      - name: THIT_CT
  - name: SAP_C11
    database: DEV_RAW
    schema: SAPC11 
    tables:
      - name: VW_VBAP
      - name: VW_VBAK
      - name: VW_VBPA
      - name: VW_VBUK
      - name: VW_VBUP
      - name: VW_LIPS
      - name: VW_LIKP
      - name: VW_VBRP
      - name: VW_VBRK
      - name: VW_T001W
      - name: VW_MAKT
      - name: VW_MARA
      - name: VW_MARC
      - name: VW_KNVH
      - name: VW_KNA1
      - name: VW_KNVV
      - name: VW_T001
      - name: VW_TVTW
      - name: VW_TSPAT
      - name: VW_TSPA
      - name: VW_TVKO
      - name: VW_THIT
      - name: VW_VBAP_CHANGES
      - name: VW_VBAK_CHANGES
      - name: VW_VBPA_CHANGES
      - name: VW_VBUK_CHANGES
      - name: VW_VBUP_CHANGES
      - name: VW_LIPS_CHANGES
      - name: VW_LIKP_CHANGES
      - name: VW_VBRP_CHANGES
      - name: VW_VBRK_CHANGES
      - name: VW_T001W_CHANGES
      - name: VW_MAKT_CHANGES
      - name: VW_MARA_CHANGES
      - name: VW_MARC_CHANGES
      - name: VW_KNVH_CHANGES
      - name: VW_KNA1_CHANGES
      - name: VW_KNVV_CHANGES
      - name: VW_T001_CHANGES
      - name: VW_TVTW_CHANGES
      - name: VW_TSPAT_CHANGES
      - name: VW_TSPA_CHANGES
      - name: VW_TVKO_CHANGES
      - name: VW_THIT_CHANGES
      - name: VBAP
      - name: VBAK
      - name: VBPA
      - name: VBUK
      - name: VBUP
      - name: LIPS
      - name: LIKP
      - name: VBRP
      - name: VBRK
      - name: T001W
      - name: MAKT
      - name: MARA
      - name: MARC
      - name: KNVH
      - name: KNA1
      - name: KNVV
      - name: T001
      - name: TVTW
      - name: TSPAT
      - name: TSPA
      - name: TVKO
      - name: THIT
      - name: VBAP_CT
      - name: VBAK_CT
      - name: VBPA_CT
      - name: VBUK_CT
      - name: VBUP_CT
      - name: LIPS_CT
      - name: LIKP_CT
      - name: VBRP_CT
      - name: VBRK_CT
      - name: T001W_CT
      - name: MAKT_CT
      - name: MARA_CT
      - name: MARC_CT
      - name: KNVH_CT
      - name: KNA1_CT
      - name: KNVV_CT
      - name: T001_CT
      - name: TVTW_CT
      - name: TSPAT_CT
      - name: TSPA_CT
      - name: TVKO_CT
      - name: THIT_CT
targets:
  - name: sapc11_tbl
    database: demo_db
    schema: sbd_demo       